### ISSUE TITLE
Nash Equillibrium List Index out of range error 

### ISSUE THREAD

**Issue by gwild37** [benedictvs/FOCS-Calculator#19]
![image](https://user-images.githubusercontent.com/45672441/141403856-45898936-0a7a-4759-87c6-1042fefcfc1f.png)

Traceback (most recent call last):
  File "/mnt/d/Dropbox/SDD_Fall21/FOCS-Calculator/main.py", line 68, in <module>
    menu()
  File "/mnt/d/Dropbox/SDD_Fall21/FOCS-Calculator/main.py", line 64, in menu
    eval(solver_pick.lower()+'solver()')
  File "<string>", line 1, in <module>
  File "/mnt/d/Dropbox/SDD_Fall21/FOCS-Calculator/nashequillibriumsolverfc.py", line 218, in nashsolver
    solution = nashsolvermodule(
  File "/mnt/d/Dropbox/SDD_Fall21/FOCS-Calculator/nashequillibriumsolverfc.py", line 145, in __init__
    self.ans, self.work = nash(payoff_matrix, player_1_strategies,
  File "/mnt/d/Dropbox/SDD_Fall21/FOCS-Calculator/nashequillibriumsolverfc.py", line 81, in nash
    if float(payoff_matrix[i][k][0]) > float(payoff_matrix[j][k][0]):
IndexError: list index out of range

**Comment by gwild37** [comment]
Think problem is solved, but I'll close after more testing
